// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.29.1
// 	protoc        v4.22.1
// source: msg.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GiftPackProto_Operator int32

const (
	GiftPackProto_Create GiftPackProto_Operator = 0 //创建
	GiftPackProto_Update GiftPackProto_Operator = 1 //更新
	GiftPackProto_GetAll GiftPackProto_Operator = 2 //获取全部
)

// Enum value maps for GiftPackProto_Operator.
var (
	GiftPackProto_Operator_name = map[int32]string{
		0: "Create",
		1: "Update",
		2: "GetAll",
	}
	GiftPackProto_Operator_value = map[string]int32{
		"Create": 0,
		"Update": 1,
		"GetAll": 2,
	}
)

func (x GiftPackProto_Operator) Enum() *GiftPackProto_Operator {
	p := new(GiftPackProto_Operator)
	*p = x
	return p
}

func (x GiftPackProto_Operator) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GiftPackProto_Operator) Descriptor() protoreflect.EnumDescriptor {
	return file_msg_proto_enumTypes[0].Descriptor()
}

func (GiftPackProto_Operator) Type() protoreflect.EnumType {
	return &file_msg_proto_enumTypes[0]
}

func (x GiftPackProto_Operator) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GiftPackProto_Operator.Descriptor instead.
func (GiftPackProto_Operator) EnumDescriptor() ([]byte, []int) {
	return file_msg_proto_rawDescGZIP(), []int{2, 0}
}

type GiftPackSlice struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Start int32 `protobuf:"zigzag32,1,opt,name=start,proto3" json:"start,omitempty"` //包含
	End   int32 `protobuf:"zigzag32,2,opt,name=end,proto3" json:"end,omitempty"`     //不包含
}

func (x *GiftPackSlice) Reset() {
	*x = GiftPackSlice{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GiftPackSlice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GiftPackSlice) ProtoMessage() {}

func (x *GiftPackSlice) ProtoReflect() protoreflect.Message {
	mi := &file_msg_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GiftPackSlice.ProtoReflect.Descriptor instead.
func (*GiftPackSlice) Descriptor() ([]byte, []int) {
	return file_msg_proto_rawDescGZIP(), []int{0}
}

func (x *GiftPackSlice) GetStart() int32 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *GiftPackSlice) GetEnd() int32 {
	if x != nil {
		return x.End
	}
	return 0
}

type GiftPack struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      uint32           `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Code    []*GiftPackSlice `protobuf:"bytes,2,rep,name=code,proto3" json:"code,omitempty"`
	Prizes  []*CPrizeItem    `protobuf:"bytes,3,rep,name=prizes,proto3" json:"prizes,omitempty"`    //奖励
	Prefix  string           `protobuf:"bytes,4,opt,name=prefix,proto3" json:"prefix,omitempty"`    //前缀（共享码）
	IsShare bool             `protobuf:"varint,5,opt,name=isShare,proto3" json:"isShare,omitempty"` //是否是共享码
	Count   uint32           `protobuf:"varint,6,opt,name=count,proto3" json:"count,omitempty"`     //数量
}

func (x *GiftPack) Reset() {
	*x = GiftPack{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GiftPack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GiftPack) ProtoMessage() {}

func (x *GiftPack) ProtoReflect() protoreflect.Message {
	mi := &file_msg_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GiftPack.ProtoReflect.Descriptor instead.
func (*GiftPack) Descriptor() ([]byte, []int) {
	return file_msg_proto_rawDescGZIP(), []int{1}
}

func (x *GiftPack) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GiftPack) GetCode() []*GiftPackSlice {
	if x != nil {
		return x.Code
	}
	return nil
}

func (x *GiftPack) GetPrizes() []*CPrizeItem {
	if x != nil {
		return x.Prizes
	}
	return nil
}

func (x *GiftPack) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *GiftPack) GetIsShare() bool {
	if x != nil {
		return x.IsShare
	}
	return false
}

func (x *GiftPack) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type GiftPackProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Op       GiftPackProto_Operator `protobuf:"varint,1,opt,name=op,proto3,enum=pb.GiftPackProto_Operator" json:"op,omitempty"`
	Giftpack *GiftPack              `protobuf:"bytes,2,opt,name=giftpack,proto3" json:"giftpack,omitempty"`
}

func (x *GiftPackProto) Reset() {
	*x = GiftPackProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GiftPackProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GiftPackProto) ProtoMessage() {}

func (x *GiftPackProto) ProtoReflect() protoreflect.Message {
	mi := &file_msg_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GiftPackProto.ProtoReflect.Descriptor instead.
func (*GiftPackProto) Descriptor() ([]byte, []int) {
	return file_msg_proto_rawDescGZIP(), []int{2}
}

func (x *GiftPackProto) GetOp() GiftPackProto_Operator {
	if x != nil {
		return x.Op
	}
	return GiftPackProto_Create
}

func (x *GiftPackProto) GetGiftpack() *GiftPack {
	if x != nil {
		return x.Giftpack
	}
	return nil
}

type GetidProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetidProto) Reset() {
	*x = GetidProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetidProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetidProto) ProtoMessage() {}

func (x *GetidProto) ProtoReflect() protoreflect.Message {
	mi := &file_msg_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetidProto.ProtoReflect.Descriptor instead.
func (*GetidProto) Descriptor() ([]byte, []int) {
	return file_msg_proto_rawDescGZIP(), []int{3}
}

func (x *GetidProto) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type WebSocketProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sender uint32 `protobuf:"varint,1,opt,name=sender,proto3" json:"sender,omitempty"` //发送者
}

func (x *WebSocketProto) Reset() {
	*x = WebSocketProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WebSocketProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebSocketProto) ProtoMessage() {}

func (x *WebSocketProto) ProtoReflect() protoreflect.Message {
	mi := &file_msg_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebSocketProto.ProtoReflect.Descriptor instead.
func (*WebSocketProto) Descriptor() ([]byte, []int) {
	return file_msg_proto_rawDescGZIP(), []int{4}
}

func (x *WebSocketProto) GetSender() uint32 {
	if x != nil {
		return x.Sender
	}
	return 0
}

var File_msg_proto protoreflect.FileDescriptor

var file_msg_proto_rawDesc = []byte{
	0x0a, 0x09, 0x6d, 0x73, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x1a,
	0x0a, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x37, 0x0a, 0x0d, 0x47,
	0x69, 0x66, 0x74, 0x50, 0x61, 0x63, 0x6b, 0x53, 0x6c, 0x69, 0x63, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x73, 0x74, 0x61, 0x72, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x11, 0x52, 0x05, 0x73, 0x74, 0x61,
	0x72, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x11, 0x52,
	0x03, 0x65, 0x6e, 0x64, 0x22, 0xb1, 0x01, 0x0a, 0x08, 0x47, 0x69, 0x66, 0x74, 0x50, 0x61, 0x63,
	0x6b, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x25, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x11, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x69, 0x66, 0x74, 0x50, 0x61, 0x63, 0x6b, 0x53, 0x6c, 0x69,
	0x63, 0x65, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x26, 0x0a, 0x06, 0x70, 0x72, 0x69, 0x7a,
	0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x50,
	0x72, 0x69, 0x7a, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x06, 0x70, 0x72, 0x69, 0x7a, 0x65, 0x73,
	0x12, 0x16, 0x0a, 0x06, 0x70, 0x72, 0x65, 0x66, 0x69, 0x78, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x70, 0x72, 0x65, 0x66, 0x69, 0x78, 0x12, 0x18, 0x0a, 0x07, 0x69, 0x73, 0x53, 0x68,
	0x61, 0x72, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x69, 0x73, 0x53, 0x68, 0x61,
	0x72, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x95, 0x01, 0x0a, 0x0d, 0x47, 0x69, 0x66,
	0x74, 0x50, 0x61, 0x63, 0x6b, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x2a, 0x0a, 0x02, 0x6f, 0x70,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1a, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x69, 0x66, 0x74,
	0x50, 0x61, 0x63, 0x6b, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74,
	0x6f, 0x72, 0x52, 0x02, 0x6f, 0x70, 0x12, 0x28, 0x0a, 0x08, 0x67, 0x69, 0x66, 0x74, 0x70, 0x61,
	0x63, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x69,
	0x66, 0x74, 0x50, 0x61, 0x63, 0x6b, 0x52, 0x08, 0x67, 0x69, 0x66, 0x74, 0x70, 0x61, 0x63, 0x6b,
	0x22, 0x2e, 0x0a, 0x08, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x12, 0x0a, 0x0a, 0x06,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x10, 0x02,
	0x22, 0x1c, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x69, 0x64, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x22, 0x28,
	0x0a, 0x0e, 0x57, 0x65, 0x62, 0x53, 0x6f, 0x63, 0x6b, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2e, 0x2f, 0x70,
	0x62, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_msg_proto_rawDescOnce sync.Once
	file_msg_proto_rawDescData = file_msg_proto_rawDesc
)

func file_msg_proto_rawDescGZIP() []byte {
	file_msg_proto_rawDescOnce.Do(func() {
		file_msg_proto_rawDescData = protoimpl.X.CompressGZIP(file_msg_proto_rawDescData)
	})
	return file_msg_proto_rawDescData
}

var file_msg_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_msg_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_msg_proto_goTypes = []interface{}{
	(GiftPackProto_Operator)(0), // 0: pb.GiftPackProto.Operator
	(*GiftPackSlice)(nil),       // 1: pb.GiftPackSlice
	(*GiftPack)(nil),            // 2: pb.GiftPack
	(*GiftPackProto)(nil),       // 3: pb.GiftPackProto
	(*GetidProto)(nil),          // 4: pb.GetidProto
	(*WebSocketProto)(nil),      // 5: pb.WebSocketProto
	(*CPrizeItem)(nil),          // 6: pb.CPrizeItem
}
var file_msg_proto_depIdxs = []int32{
	1, // 0: pb.GiftPack.code:type_name -> pb.GiftPackSlice
	6, // 1: pb.GiftPack.prizes:type_name -> pb.CPrizeItem
	0, // 2: pb.GiftPackProto.op:type_name -> pb.GiftPackProto.Operator
	2, // 3: pb.GiftPackProto.giftpack:type_name -> pb.GiftPack
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_msg_proto_init() }
func file_msg_proto_init() {
	if File_msg_proto != nil {
		return
	}
	file_base_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_msg_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GiftPackSlice); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GiftPack); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GiftPackProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetidProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WebSocketProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_msg_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_msg_proto_goTypes,
		DependencyIndexes: file_msg_proto_depIdxs,
		EnumInfos:         file_msg_proto_enumTypes,
		MessageInfos:      file_msg_proto_msgTypes,
	}.Build()
	File_msg_proto = out.File
	file_msg_proto_rawDesc = nil
	file_msg_proto_goTypes = nil
	file_msg_proto_depIdxs = nil
}
