// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.22.1
// source: service.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	SrvService_SrvSvc_FullMethodName = "/pb.SrvService/SrvSvc"
)

// SrvServiceClient is the client API for SrvService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SrvServiceClient interface {
	SrvSvc(ctx context.Context, in *SvcReq, opts ...grpc.CallOption) (*SvcResp, error)
}

type srvServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSrvServiceClient(cc grpc.ClientConnInterface) SrvServiceClient {
	return &srvServiceClient{cc}
}

func (c *srvServiceClient) SrvSvc(ctx context.Context, in *SvcReq, opts ...grpc.CallOption) (*SvcResp, error) {
	out := new(SvcResp)
	err := c.cc.Invoke(ctx, SrvService_SrvSvc_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SrvServiceServer is the server API for SrvService service.
// All implementations must embed UnimplementedSrvServiceServer
// for forward compatibility
type SrvServiceServer interface {
	SrvSvc(context.Context, *SvcReq) (*SvcResp, error)
	mustEmbedUnimplementedSrvServiceServer()
}

// UnimplementedSrvServiceServer must be embedded to have forward compatible implementations.
type UnimplementedSrvServiceServer struct {
}

func (UnimplementedSrvServiceServer) SrvSvc(context.Context, *SvcReq) (*SvcResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SrvSvc not implemented")
}
func (UnimplementedSrvServiceServer) mustEmbedUnimplementedSrvServiceServer() {}

// UnsafeSrvServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SrvServiceServer will
// result in compilation errors.
type UnsafeSrvServiceServer interface {
	mustEmbedUnimplementedSrvServiceServer()
}

func RegisterSrvServiceServer(s grpc.ServiceRegistrar, srv SrvServiceServer) {
	s.RegisterService(&SrvService_ServiceDesc, srv)
}

func _SrvService_SrvSvc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SvcReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SrvServiceServer).SrvSvc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SrvService_SrvSvc_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SrvServiceServer).SrvSvc(ctx, req.(*SvcReq))
	}
	return interceptor(ctx, in, info, handler)
}

// SrvService_ServiceDesc is the grpc.ServiceDesc for SrvService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SrvService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.SrvService",
	HandlerType: (*SrvServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SrvSvc",
			Handler:    _SrvService_SrvSvc_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}
