apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: default
spec:
  type: NodePort
  ports:
  - name: db
    nodePort: 30920
    port: 9200
    protocol: TCP
    targetPort: 9200
  - name: transport
    nodePort: 30930
    port: 9300
    protocol: TCP
    targetPort: 9300    
  selector:
    app: lark-es
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lark-es
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lark-es
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: lark-es
    spec:
      containers:
      - env:
        - name: discovery.type
          value: single-node
        - name: ES_JAVA_OPTS
          value: "-Xms1g -Xmx1g"
        - name: xpack.security.enabled
          value: "false"
        - name: READINESS_PROBE_PROTOCOL
          value: http
        image: elasticsearch:8.5.3
        name: elasticsearch
        ports:
        - containerPort: 9200
          name: db
          protocol: TCP
        - containerPort: 9300
          name: tramsport
          protocol: TCP