apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis-cluster
  name: lark-redis-client
  namespace: default
spec:
  ports:
  - name: lark-redis-6379
    port: 6379
    protocol: TCP
    targetPort: 6379
    nodePort: 30637
  selector:
    app: lark-redis
  sessionAffinity: None
  type: NodePort